import { cricketInningsMetrics } from "@sports-fiesta/domain";
import { useLocalSearchParams } from "expo-router";
import { CalendarDays, MapPin } from "lucide-react-native";
import { ScrollView, StyleSheet, Text, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { Card, Section, StateView } from "@/components/screen";
import { usePublicCollection, usePublicDocument } from "@/hooks/use-public-data";
import { colors } from "@/lib/theme";
import type { PublicMatch, PublicPlayer, PublicTeam } from "@/lib/types";

export default function MatchDetailScreen() {
  const { matchId } = useLocalSearchParams<{ matchId: string }>();
  const match = usePublicDocument<PublicMatch>("matches", matchId);
  const teams = usePublicCollection<PublicTeam>("teams");
  const players = usePublicCollection<PublicPlayer>("players");
  if (match.loading || teams.loading || players.loading) return <SafeAreaView style={styles.safe}><StateView loading /></SafeAreaView>;
  if (match.error || teams.error || players.error) return <SafeAreaView style={styles.safe}><StateView error={match.error || teams.error || players.error} /></SafeAreaView>;
  if (!match.data) return <SafeAreaView style={styles.safe}><StateView empty={<Text style={styles.muted}>This match is not available.</Text>} /></SafeAreaView>;
  const item = match.data;
  const teamName = (id: string) => teams.data.find((team) => team.id === id)?.name ?? "Team";
  const playerName = (id?: string | null) => players.data.find((player) => player.id === id)?.name ?? "Player";
  return <SafeAreaView style={styles.safe} edges={["bottom"]}><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}><View><Text style={styles.eyebrow}>{item.sport.toUpperCase()} · {item.stage.toUpperCase()}</Text><Text style={styles.title}>{teamName(item.homeTeamId)} vs {teamName(item.awayTeamId)}</Text><Text style={[styles.status, item.status === "live" && { color: colors.danger }]}>{item.status.toUpperCase()}</Text></View>{item.sport === "cricket" ? <CricketDetail match={item} teamName={teamName} playerName={playerName} /> : <FieldDetail match={item} teamName={teamName} playerName={playerName} />}<Card><View style={styles.meta}><CalendarDays color={colors.muted} size={18} /><Text style={styles.muted}>{formatDate(item.startsAt)}</Text></View><View style={styles.meta}><MapPin color={colors.muted} size={18} /><Text style={styles.muted}>{item.venue || "Venue pending"}</Text></View>{item.resultText ? <Text style={styles.result}>{item.resultText}</Text> : null}</Card></ScrollView></SafeAreaView>;
}

function FieldDetail({ match, teamName, playerName }: { match: PublicMatch; teamName: (id: string) => string; playerName: (id?: string) => string }) {
  const score = match.fieldState?.score ?? { [match.homeTeamId]: 0, [match.awayTeamId]: 0 };
  const events = match.fieldState?.events ?? [];
  return <><Card><View style={styles.scoreRow}><View style={styles.scoreTeam}><Text style={styles.teamName}>{teamName(match.homeTeamId)}</Text><Text style={styles.bigScore}>{score[match.homeTeamId]}</Text></View><Text style={styles.vs}>VS</Text><View style={[styles.scoreTeam, { alignItems: "flex-end" }]}><Text style={[styles.teamName, { textAlign: "right" }]}>{teamName(match.awayTeamId)}</Text><Text style={styles.bigScore}>{score[match.awayTeamId]}</Text></View></View></Card><Section title="Match events">{events.length ? <View style={styles.list}>{[...events].reverse().map((event, index) => <Card key={String(event.id ?? index)}><View style={styles.event}><View><Text style={styles.eventTitle}>{String(event.type).replaceAll("-", " ").toUpperCase()}</Text><Text style={styles.muted}>{playerName(String(event.playerId ?? ""))}</Text></View><Text style={styles.eventTeam}>{teamName(String(event.teamId))}</Text></View></Card>)}</View> : <StateView empty={<Text style={styles.muted}>No events have been recorded.</Text>} />}</Section><Lineups match={match} teamName={teamName} playerName={playerName} /></>;
}

function CricketDetail({ match, teamName, playerName }: { match: PublicMatch; teamName: (id: string) => string; playerName: (id?: string | null) => string }) {
  const innings = match.cricket?.innings ?? [];
  const index = match.cricket?.currentInnings ?? innings.length - 1;
  const current = innings[index]?.state;
  if (!current) return <StateView empty={<Text style={styles.muted}>The scorecard will appear when scoring starts.</Text>} />;
  const target = index % 2 === 1 ? (innings[index - 1]?.state.score ?? 0) + 1 : null;
  const metrics = cricketInningsMetrics(current, target);
  return <><Card><Text style={styles.batting}>{teamName(current.battingTeamId)} BATTING</Text><Text style={styles.cricketScore}>{current.score}/{current.wickets}</Text><Text style={styles.inningsMeta}>{current.overs} overs · RR {metrics.runRate.toFixed(2)}</Text>{target ? <Text style={styles.chase}>Need {metrics.runsRequired} from {metrics.ballsRemaining} balls · RRR {metrics.requiredRunRate === Infinity ? "-" : metrics.requiredRunRate.toFixed(2)}</Text> : null}</Card><Section title="This over"><View style={styles.balls}>{current.events.slice(-12).map((event) => <View key={event.id} style={[styles.ball, event.dismissal && styles.wicketBall]}><Text style={styles.ballText}>{event.dismissal ? "W" : event.extraType === "wide" ? "Wd" : event.extraType === "no-ball" ? "Nb" : event.totalRuns}</Text></View>)}</View></Section><Section title="Batting"><View style={styles.table}><TableHeader labels={["Batter", "R", "B", "SR"]} />{Object.values(current.batters).map((batter) => <TableRow key={batter.playerId} values={[playerName(batter.playerId), batter.runs, batter.balls, batter.balls ? ((batter.runs / batter.balls) * 100).toFixed(1) : "0.0"]} />)}</View></Section><Section title="Bowling"><View style={styles.table}><TableHeader labels={["Bowler", "O", "R", "W"]} />{Object.values(current.bowlers).map((bowler) => <TableRow key={bowler.playerId} values={[playerName(bowler.playerId), `${Math.floor(bowler.legalBalls / 6)}.${bowler.legalBalls % 6}`, bowler.runs, bowler.wickets]} />)}</View></Section><Card><Text style={styles.eventTitle}>EXTRAS</Text><Text style={styles.extras}>Wd {current.extras.wides} · Nb {current.extras.noBalls} · B {current.extras.byes} · LB {current.extras.legByes} · P {current.extras.penalty}</Text></Card></>;
}

function Lineups({ match, teamName, playerName }: { match: PublicMatch; teamName: (id: string) => string; playerName: (id: string) => string }) { const entries = Object.entries(match.lineups ?? {}); if (!entries.length) return null; return <Section title="Lineups"><View style={styles.list}>{entries.map(([teamId, lineup]) => <Card key={teamId}><Text style={styles.eventTitle}>{teamName(teamId)}</Text><Text style={[styles.muted, { marginTop: 8 }]}>{lineup.starters.map(playerName).join(", ") || "Not published"}</Text></Card>)}</View></Section>; }
function TableHeader({ labels }: { labels: string[] }) { return <View style={styles.tableRow}>{labels.map((label, index) => <Text key={label} style={[styles.headerCell, index === 0 && styles.firstCell]}>{label}</Text>)}</View>; }
function TableRow({ values }: { values: (string | number)[] }) { return <View style={styles.tableRow}>{values.map((value, index) => <Text key={index} numberOfLines={1} style={[styles.cell, index === 0 && styles.firstCell]}>{value}</Text>)}</View>; }
function formatDate(value: string) { const date = new Date(value); return Number.isNaN(date.valueOf()) ? "Schedule pending" : new Intl.DateTimeFormat("en-IN", { dateStyle: "medium", timeStyle: "short" }).format(date); }

const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: colors.background, padding: 18 }, content: { paddingBottom: 32, gap: 22 }, eyebrow: { color: colors.primary, fontSize: 12, fontWeight: "900" }, title: { color: colors.text, fontSize: 25, lineHeight: 31, fontWeight: "800", marginTop: 6 }, status: { color: colors.muted, fontSize: 12, fontWeight: "900", marginTop: 8 }, scoreRow: { flexDirection: "row", alignItems: "center", gap: 12 }, scoreTeam: { flex: 1, gap: 8 }, teamName: { color: colors.text, fontSize: 15, lineHeight: 20, fontWeight: "700" }, bigScore: { color: colors.text, fontSize: 50, fontWeight: "900" }, vs: { color: colors.muted, fontSize: 11, fontWeight: "900" }, list: { gap: 9 }, event: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", gap: 12 }, eventTitle: { color: colors.text, fontSize: 12, fontWeight: "900" }, eventTeam: { color: colors.muted, fontSize: 12, textAlign: "right", flexShrink: 1 }, muted: { color: colors.muted, fontSize: 14, lineHeight: 20, flexShrink: 1 }, batting: { color: colors.primary, fontSize: 12, fontWeight: "900", textAlign: "center" }, cricketScore: { color: colors.text, fontSize: 52, fontWeight: "900", textAlign: "center", marginTop: 8 }, inningsMeta: { color: colors.muted, fontSize: 14, textAlign: "center", marginTop: 4 }, chase: { color: colors.text, fontSize: 15, fontWeight: "700", textAlign: "center", marginTop: 12 }, balls: { flexDirection: "row", flexWrap: "wrap", gap: 8 }, ball: { minWidth: 42, height: 42, borderRadius: 7, borderWidth: 1, borderColor: colors.border, alignItems: "center", justifyContent: "center", paddingHorizontal: 6 }, wicketBall: { borderColor: colors.danger, backgroundColor: "#351818" }, ballText: { color: colors.text, fontSize: 14, fontWeight: "900" }, table: { borderWidth: 1, borderColor: colors.border, borderRadius: 8, overflow: "hidden" }, tableRow: { flexDirection: "row", minHeight: 43, alignItems: "center", borderBottomWidth: 1, borderBottomColor: colors.border, paddingHorizontal: 10 }, headerCell: { flex: 0.6, color: colors.muted, textAlign: "right", fontSize: 11, fontWeight: "900" }, cell: { flex: 0.6, color: colors.text, textAlign: "right", fontSize: 13 }, firstCell: { flex: 2.2, textAlign: "left" }, extras: { color: colors.muted, fontSize: 14, marginTop: 8 }, meta: { flexDirection: "row", alignItems: "center", gap: 9, marginBottom: 10 }, result: { color: colors.text, fontSize: 15, fontWeight: "700", borderTopWidth: 1, borderTopColor: colors.border, paddingTop: 12, marginTop: 3 } });
