import { Image } from "expo-image";
import type { PropsWithChildren, ReactNode } from "react";
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View, type ViewStyle } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { useAppTheme, type ThemeColors } from "@/lib/theme";

export function Screen({ title, subtitle, children }: PropsWithChildren<{ title: string; subtitle?: string }>) {
  const { colors } = useAppTheme(); const styles = makeStyles(colors);
  return <SafeAreaView style={styles.safe} edges={["top", "left", "right"]}><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}><View style={styles.brand}><Image source={require("../../../assets/images/logo.png")} accessibilityLabel="Sports Fiesta logo" contentFit="contain" style={styles.logo} /><Text style={styles.brandText}>SPORTS FIESTA</Text></View><View><Text style={styles.title}>{title}</Text>{subtitle ? <Text style={styles.subtitle}>{subtitle}</Text> : null}</View>{children}</ScrollView></SafeAreaView>;
}
export function Section({ title, children }: PropsWithChildren<{ title: string }>) { const { colors } = useAppTheme(); return <View style={base.section}><Text style={[base.sectionTitle, { color: colors.text }]}>{title}</Text>{children}</View>; }
export function Card({ children, style }: PropsWithChildren<{ style?: ViewStyle | ViewStyle[] }>) { const { colors } = useAppTheme(); return <View style={[base.card, { borderColor: colors.border, backgroundColor: colors.surface }, style]}>{children}</View>; }
export function Badge({ status }: { status: string }) { const { colors } = useAppTheme(); const live = ["live", "innings-break", "super-over"].includes(status); const completed = status === "completed"; const color = live ? "#22c55e" : completed ? colors.muted : "#3b82f6"; return <View style={[base.badge, { borderColor: color, backgroundColor: `${color}20` }]}><View style={[base.badgeDot, { backgroundColor: color }]} /><Text style={[base.badgeText, { color }]}>{live ? "LIVE" : completed ? "COMPLETED" : "UPCOMING"}</Text></View>; }
export function Button({ label, onPress, disabled, secondary }: { label: string; onPress: () => void; disabled?: boolean; secondary?: boolean }) { const { colors } = useAppTheme(); return <Pressable accessibilityRole="button" disabled={disabled} onPress={onPress} style={({ pressed }) => [base.button, { backgroundColor: secondary ? colors.surfaceMuted : colors.primary, borderColor: secondary ? colors.border : colors.primary }, (pressed || disabled) && { opacity: 0.6 }]}><Text style={[base.buttonText, { color: secondary ? colors.text : colors.background }]}>{label}</Text></Pressable>; }
export function StateView({ loading, error, empty }: { loading?: boolean; error?: string | null; empty?: ReactNode }) { const { colors } = useAppTheme(); if (loading) return <View style={[base.state, { borderColor: colors.border }]}><ActivityIndicator color={colors.primary} /><Text style={{ color: colors.muted }}>Loading tournament data</Text></View>; if (error) return <View style={[base.state, { borderColor: colors.border }]}><Text style={{ color: colors.danger, fontWeight: "700" }}>Live data is unavailable</Text><Text style={{ color: colors.muted, textAlign: "center" }}>{error}</Text></View>; return empty ? <View style={[base.state, { borderColor: colors.border }]}>{empty}</View> : null; }

const makeStyles = (colors: ThemeColors) => StyleSheet.create({ safe: { flex: 1, backgroundColor: colors.background }, content: { padding: 18, paddingBottom: 100, gap: 24 }, brand: { flexDirection: "row", alignItems: "center", gap: 10 }, logo: { width: 42, height: 42 }, brandText: { color: colors.muted, fontSize: 12, fontWeight: "800" }, title: { color: colors.text, fontSize: 30, lineHeight: 36, fontWeight: "800" }, subtitle: { color: colors.muted, fontSize: 15, lineHeight: 22, marginTop: 6 } });
const base = StyleSheet.create({ section: { gap: 12 }, sectionTitle: { fontSize: 20, fontWeight: "800" }, card: { borderWidth: 1, borderRadius: 10, padding: 16 }, badge: { flexDirection: "row", alignItems: "center", gap: 5, borderWidth: 1, borderRadius: 999, paddingHorizontal: 8, paddingVertical: 4 }, badgeDot: { width: 6, height: 6, borderRadius: 3 }, badgeText: { fontSize: 9, fontWeight: "900" }, button: { minHeight: 46, borderWidth: 1, borderRadius: 8, paddingHorizontal: 14, alignItems: "center", justifyContent: "center" }, buttonText: { fontSize: 14, fontWeight: "800" }, state: { minHeight: 140, borderWidth: 1, borderRadius: 10, padding: 20, alignItems: "center", justifyContent: "center", gap: 8 } });
