import { useState } from "react";
import { Pressable, StyleSheet, Text, View } from "react-native";
import { Card, Screen, Section, StateView } from "@/components/ui/primitives";
import { usePublicCollection, usePublicDocument } from "@/hooks/use-public-data";
import { useAppTheme } from "@/lib/theme";
import type { CricketLeaderboard, FieldLeaderboard, PublicMatch, PublicPlayer, PublicTeam, Sport, SportStandingDocument, SportStandingRow } from "@/lib/types";

const sports: { id: Sport; name: string; detail: string }[] = [{ id: "cricket", name: "Cricket", detail: "Runs, wickets and net run rate" }, { id: "football", name: "Football", detail: "Goals, points and clean sheets" }, { id: "handball", name: "Handball", detail: "Goals, points and rankings" }];

export default function SportsScreen() {
  const { colors } = useAppTheme(); const [selected, setSelected] = useState<Sport>("cricket");
  const teams = usePublicCollection<PublicTeam>("teams"); const players = usePublicCollection<PublicPlayer>("players"); const matches = usePublicCollection<PublicMatch>("matches");
  const cricket = usePublicDocument<SportStandingDocument>("standings", "cricket"); const football = usePublicDocument<SportStandingDocument>("standings", "football"); const handball = usePublicDocument<SportStandingDocument>("standings", "handball");
  const cricketLeaders = usePublicDocument<CricketLeaderboard>("leaderboards", "cricket"); const footballLeaders = usePublicDocument<FieldLeaderboard>("leaderboards", "football"); const handballLeaders = usePublicDocument<FieldLeaderboard>("leaderboards", "handball");
  const standings = { cricket: cricket.data?.rows ?? [], football: football.data?.rows ?? [], handball: handball.data?.rows ?? [] };
  const leaderboards = { cricket: cricketLeaders.data, football: footballLeaders.data, handball: handballLeaders.data };
  const teamName = (id: string) => teams.data.find((team) => team.id === id)?.name ?? "Team"; const playerName = (id: string) => players.data.find((player) => player.id === id)?.name ?? "Player";
  if ([teams, players, matches, cricket, football, handball].some((state) => state.loading)) return <Screen title="Sports"><StateView loading /></Screen>;
  return <Screen title="Sports" subtitle="Team tables and leading individual performances.">
    <View style={styles.sportList}>{sports.map((sport) => <Pressable accessibilityRole="button" accessibilityState={{ selected: selected === sport.id }} key={sport.id} onPress={() => setSelected(sport.id)}><Card style={selected === sport.id ? { borderColor: colors.primary, borderWidth: 2 } : undefined}><View style={styles.sportRow}><View style={styles.grow}><Text style={[styles.sportName, { color: colors.text }]}>{sport.name}</Text><Text style={[styles.detail, { color: colors.muted }]}>{sport.detail}</Text></View><Text style={[styles.open, { color: colors.primary }]}>{selected === sport.id ? "OPEN" : "VIEW"}</Text></View><MiniRanking rows={standings[sport.id]} teamName={teamName} /></Card></Pressable>)}</View>
    <Section title={`${sports.find((sport) => sport.id === selected)?.name} points table`}><Card><PointsTable rows={standings[selected]} teamName={teamName} /></Card></Section>
    <TopPerformers sport={selected} data={leaderboards[selected]} matches={matches.data} playerName={playerName} teamName={teamName} />
  </Screen>;
}

function MiniRanking({ rows, teamName }: { rows: SportStandingRow[]; teamName: (id: string) => string }) { const { colors } = useAppTheme(); return <View style={[styles.mini, { borderTopColor: colors.border }]}>{rows.slice(0, 4).map((row, index) => <Text key={row.teamId} numberOfLines={1} style={[styles.miniText, { color: colors.muted }]}>{index + 1}. {teamName(row.teamId)}</Text>)}</View>; }
function PointsTable({ rows, teamName }: { rows: SportStandingRow[]; teamName: (id: string) => string }) { const { colors } = useAppTheme(); if (!rows.length) return <Text style={{ color: colors.muted }}>Rankings will appear after match results are published.</Text>; return <View>{rows.map((row, index) => <View key={row.teamId} style={[styles.tableRow, index > 0 && { borderTopColor: colors.border, borderTopWidth: 1 }]}><Text style={[styles.rank, { color: colors.primary }]}>{row.rank ?? index + 1}</Text><View style={styles.grow}><Text style={[styles.team, { color: colors.text }]}>{teamName(row.teamId)}</Text><Text style={[styles.record, { color: colors.muted }]}>P {row.played} · W {row.wins} · L {row.losses} · {"draws" in row ? `D ${row.draws ?? 0}` : `T ${row.ties ?? 0}`}</Text></View><Text style={[styles.points, { color: colors.text }]}>{row.points}</Text></View>)}</View>; }
function TopPerformers({ sport, data, matches, playerName, teamName }: { sport: Sport; data?: CricketLeaderboard | FieldLeaderboard | null; matches: PublicMatch[]; playerName: (id: string) => string; teamName: (id: string) => string }) {
  const { colors } = useAppTheme();
  if (sport === "cricket") { const board = data as CricketLeaderboard | null; return <Section title="Top performers"><View style={styles.performers}><LeaderboardCard title="Top batsmen" rows={(board?.orangeCap ?? []).slice(0, 3).map((row) => ({ name: playerName(row.playerId), value: `${row.runs} runs` }))} /><LeaderboardCard title="Top bowlers" rows={(board?.purpleCap ?? []).slice(0, 3).map((row) => ({ name: playerName(row.playerId), value: `${row.wickets} wickets` }))} /></View></Section>; }
  const board = data as FieldLeaderboard | null; const cleanSheets = new Map<string, number>(); for (const match of matches.filter((item) => item.sport === sport && item.status === "completed")) { const score = match.fieldState?.score; if (!score) continue; if ((score[match.awayTeamId] ?? 0) === 0) cleanSheets.set(match.homeTeamId, (cleanSheets.get(match.homeTeamId) ?? 0) + 1); if ((score[match.homeTeamId] ?? 0) === 0) cleanSheets.set(match.awayTeamId, (cleanSheets.get(match.awayTeamId) ?? 0) + 1); }
  const cleanRows = [...cleanSheets.entries()].sort((a, b) => b[1] - a[1]).slice(0, 3).map(([teamId, count]) => ({ name: teamName(teamId), value: `${count} clean sheets` }));
  return <Section title="Top performers"><View style={styles.performers}><LeaderboardCard title="Top scorers" rows={(board?.topScorers ?? []).slice(0, 3).map((row) => ({ name: playerName(row.playerId), value: `${row.goals} goals` }))} /><LeaderboardCard title="Clean sheets" rows={cleanRows} /></View>{!board?.topScorers?.length ? <Text style={{ color: colors.muted }}>Performance leaders will appear after events are recorded.</Text> : null}</Section>;
}
function LeaderboardCard({ title, rows }: { title: string; rows: { name: string; value: string }[] }) { const { colors } = useAppTheme(); return <Card style={styles.leaderCard}><Text style={[styles.leaderTitle, { color: colors.text }]}>{title}</Text>{rows.length ? rows.map((row, index) => <View key={`${row.name}-${index}`} style={styles.leaderRow}><Text numberOfLines={1} style={[styles.leaderName, { color: colors.muted }]}>{index + 1}. {row.name}</Text><Text style={[styles.leaderValue, { color: colors.primary }]}>{row.value}</Text></View>) : <Text style={{ color: colors.muted, fontSize: 12, marginTop: 9 }}>No data yet</Text>}</Card>; }
const styles = StyleSheet.create({ sportList: { gap: 10 }, sportRow: { flexDirection: "row", alignItems: "center", gap: 12 }, grow: { flex: 1 }, sportName: { fontSize: 18, fontWeight: "900" }, detail: { fontSize: 12, marginTop: 4 }, open: { fontSize: 10, fontWeight: "900" }, mini: { borderTopWidth: 1, marginTop: 13, paddingTop: 10, gap: 4 }, miniText: { fontSize: 11 }, tableRow: { minHeight: 58, flexDirection: "row", alignItems: "center", gap: 10 }, rank: { width: 22, fontSize: 15, fontWeight: "900" }, team: { fontSize: 14, fontWeight: "800" }, record: { fontSize: 11, marginTop: 3 }, points: { fontSize: 22, fontWeight: "900" }, performers: { gap: 10 }, leaderCard: { flex: 1 }, leaderTitle: { fontSize: 15, fontWeight: "900" }, leaderRow: { flexDirection: "row", justifyContent: "space-between", gap: 10, marginTop: 9 }, leaderName: { flex: 1, fontSize: 12 }, leaderValue: { fontSize: 11, fontWeight: "800" } });
