import { S9_TEAMS } from "@sports-fiesta/domain";
import { StyleSheet, Text, useWindowDimensions, View } from "react-native";
import Svg, { Rect } from "react-native-svg";
import { Card, Screen, StateView } from "@/components/screen";
import { usePublicDocument } from "@/hooks/use-public-data";
import { colors } from "@/lib/theme";
import type { OverallDocument } from "@/lib/types";

export default function TeamsScreen() {
  const standings = usePublicDocument<OverallDocument>("standings", "overall");
  const { width } = useWindowDimensions();
  const rows = S9_TEAMS.map((team, index) => { const stored = standings.data?.rows.find((row) => row.teamId === team.id); return { team, rank: stored?.rank ?? index + 1, football: stored?.football ?? 0, handball: stored?.handball ?? 0, cricket: stored?.cricket ?? 0, discipline: stored?.discipline ?? 0, total: stored?.total ?? 0 }; }).sort((a, b) => b.total - a.total || a.rank - b.rank);
  const max = Math.max(1, ...rows.map((row) => Math.max(0, row.football) + Math.max(0, row.handball) + Math.max(0, row.cricket) + Math.max(0, row.discipline)));
  const chartWidth = Math.max(260, width - 70);
  return <Screen title="Team standings" subtitle="Placement and discipline points across every sport.">{standings.loading ? <StateView loading /> : null}{standings.error ? <StateView error={standings.error} /> : null}<Card><View style={styles.legend}>{[[colors.football, "Football"], [colors.handball, "Handball"], [colors.cricket, "Cricket"], [colors.discipline, "Discipline"]].map(([color, label]) => <View key={label} style={styles.legendItem}><View style={[styles.dot, { backgroundColor: color }]} /><Text style={styles.legendText}>{label}</Text></View>)}</View><View style={styles.chart}>{rows.map((row) => { let x = 0; const values = [[row.football, colors.football], [row.handball, colors.handball], [row.cricket, colors.cricket], [Math.max(0, row.discipline), colors.discipline]] as const; return <View key={row.team.id} style={styles.chartRow}><Text style={styles.short}>{row.team.shortName}</Text><Svg width={chartWidth - 100} height={24}>{values.map(([value, color], index) => { const segment = ((Math.max(0, value) / max) * (chartWidth - 100)); const rect = <Rect key={index} x={x} y={2} width={segment} height={20} fill={color} rx={index === values.length - 1 ? 4 : 0} />; x += segment; return rect; })}</Svg><Text style={styles.total}>{row.total}</Text></View>; })}</View></Card><View style={styles.rows}>{rows.map((row, index) => <Card key={row.team.id}><View style={styles.standing}><View style={styles.rank}><Text style={styles.rankText}>{index + 1}</Text></View><View style={[styles.teamDot, { backgroundColor: row.team.accentColor }]} /><View style={styles.name}><Text style={styles.teamName}>{row.team.name}</Text><Text style={styles.breakdown}>F {row.football} · H {row.handball} · C {row.cricket} · D {row.discipline}</Text></View><Text style={styles.points}>{row.total}</Text></View></Card>)}</View></Screen>;
}

const styles = StyleSheet.create({ legend: { flexDirection: "row", flexWrap: "wrap", gap: 12 }, legendItem: { flexDirection: "row", alignItems: "center", gap: 6 }, dot: { width: 9, height: 9, borderRadius: 2 }, legendText: { color: colors.muted, fontSize: 12 }, chart: { marginTop: 18, gap: 13 }, chartRow: { flexDirection: "row", alignItems: "center", gap: 8 }, short: { width: 55, color: colors.text, fontSize: 12, fontWeight: "700" }, total: { width: 22, color: colors.text, fontSize: 14, fontWeight: "800", textAlign: "right" }, rows: { gap: 10 }, standing: { flexDirection: "row", alignItems: "center", gap: 11 }, rank: { width: 30, height: 30, borderRadius: 6, backgroundColor: colors.surfaceMuted, alignItems: "center", justifyContent: "center" }, rankText: { color: colors.muted, fontWeight: "800" }, teamDot: { width: 11, height: 11, borderRadius: 3, borderWidth: 1, borderColor: colors.border }, name: { flex: 1 }, teamName: { color: colors.text, fontSize: 15, fontWeight: "700" }, breakdown: { color: colors.muted, fontSize: 12, marginTop: 3 }, points: { color: colors.text, fontSize: 24, fontWeight: "900" } });
