import { LockKeyhole } from "lucide-react-native";
import { useRouter } from "expo-router";
import { useState } from "react";
import { KeyboardAvoidingView, Platform, StyleSheet, Text, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { Action, Card, Field } from "@/components/ui";
import { colors } from "@/lib/theme";
import { useOrganizerAuth } from "@/providers/auth-provider";
export default function LoginScreen() { const { login } = useOrganizerAuth(); const router = useRouter(); const [name, setName] = useState(""); const [pin, setPin] = useState(""); const [pending, setPending] = useState(false); const [error, setError] = useState(""); async function submit() { setPending(true); setError(""); try { await login(name.trim(), pin); router.replace("/home"); } catch (cause) { setError(cause instanceof Error ? cause.message : "Organizer login failed."); } finally { setPending(false); } } return <SafeAreaView style={styles.safe}><KeyboardAvoidingView style={styles.center} behavior={Platform.OS === "ios" ? "padding" : undefined}><Card><View style={styles.mark}><Text style={styles.markText}>S9</Text></View><Text style={styles.title}>Organizer access</Text><Text style={styles.subtitle}>Use the private Sports Fiesta PIN. This device will remain signed in.</Text><View style={styles.form}><Field label="Display name" value={name} onChangeText={setName} autoCapitalize="words" /><Field label="Organizer PIN" value={pin} onChangeText={setPin} keyboardType="number-pad" secureTextEntry maxLength={8} />{error ? <Text style={styles.error}>{error}</Text> : null}<Action label={pending ? "Checking access" : "Continue"} disabled={pending || name.trim().length < 2 || pin.length < 5} onPress={submit} icon={<LockKeyhole color={colors.background} size={18} />} /></View></Card></KeyboardAvoidingView></SafeAreaView>; }
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: colors.background }, center: { flex: 1, justifyContent: "center", padding: 18 }, mark: { width: 48, height: 48, borderRadius: 8, backgroundColor: colors.primary, alignItems: "center", justifyContent: "center" }, markText: { color: colors.background, fontWeight: "900" }, title: { color: colors.text, fontSize: 26, fontWeight: "800", marginTop: 20 }, subtitle: { color: colors.muted, fontSize: 15, lineHeight: 22, marginTop: 6 }, form: { gap: 15, marginTop: 24 }, error: { color: colors.danger, fontSize: 14 } });
