import type { PropsWithChildren, ReactNode } from "react";
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, TextInput, View, type TextInputProps } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { colors } from "@/lib/theme";
export function Screen({ title, subtitle, children }: PropsWithChildren<{ title: string; subtitle?: string }>) { return <SafeAreaView style={styles.safe} edges={["top", "left", "right"]}><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><View style={styles.brand}><View style={styles.mark}><Text style={styles.markText}>SPTC</Text></View><Text style={styles.brandText}>ORGANIZER</Text></View><View><Text style={styles.title}>{title}</Text>{subtitle ? <Text style={styles.subtitle}>{subtitle}</Text> : null}</View>{children}</ScrollView></SafeAreaView>; }
export function Card({ children }: PropsWithChildren) { return <View style={styles.card}>{children}</View>; }
export function Section({ title, children }: PropsWithChildren<{ title: string }>) { return <View style={styles.section}><Text style={styles.sectionTitle}>{title}</Text>{children}</View>; }
export function Field({ label, ...props }: TextInputProps & { label: string }) { return <View style={styles.field}><Text style={styles.label}>{label}</Text><TextInput placeholderTextColor={colors.muted} style={styles.input} {...props} /></View>; }
export function Action({ label, onPress, disabled, variant = "primary", icon }: { label: string; onPress: () => void; disabled?: boolean; variant?: "primary" | "outline" | "danger"; icon?: ReactNode }) { return <Pressable accessibilityRole="button" onPress={onPress} disabled={disabled} style={({ pressed }) => [styles.button, variant === "outline" && styles.buttonOutline, variant === "danger" && styles.buttonDanger, (pressed || disabled) && { opacity: 0.55 }]}>{icon}<Text style={[styles.buttonText, variant !== "primary" && { color: variant === "danger" ? colors.danger : colors.text }]}>{label}</Text></Pressable>; }
export function StateView({ loading, error, text }: { loading?: boolean; error?: string | null; text?: string }) { return <View style={styles.state}>{loading ? <ActivityIndicator color={colors.primary} /> : null}<Text style={error ? styles.error : styles.muted}>{error || text || "Loading"}</Text></View>; }
export const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: colors.background }, content: { padding: 18, paddingBottom: 96, gap: 24 }, brand: { flexDirection: "row", alignItems: "center", gap: 10 }, mark: { minWidth: 44, height: 38, paddingHorizontal: 5, borderRadius: 8, alignItems: "center", justifyContent: "center", backgroundColor: colors.primary }, markText: { color: colors.background, fontSize: 11, fontWeight: "900" }, brandText: { color: colors.muted, fontSize: 12, fontWeight: "900" }, title: { color: colors.text, fontSize: 30, lineHeight: 36, fontWeight: "800" }, subtitle: { color: colors.muted, fontSize: 15, lineHeight: 22, marginTop: 6 }, card: { borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface, borderRadius: 8, padding: 16 }, section: { gap: 12 }, sectionTitle: { color: colors.text, fontSize: 20, fontWeight: "800" }, field: { gap: 7 }, label: { color: colors.text, fontSize: 13, fontWeight: "700" }, input: { minHeight: 48, borderWidth: 1, borderColor: colors.border, borderRadius: 8, color: colors.text, backgroundColor: colors.surface, paddingHorizontal: 13, fontSize: 16 }, button: { minHeight: 48, borderRadius: 8, paddingHorizontal: 16, flexDirection: "row", gap: 8, alignItems: "center", justifyContent: "center", backgroundColor: colors.primary }, buttonOutline: { backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border }, buttonDanger: { backgroundColor: "#351818", borderWidth: 1, borderColor: colors.danger }, buttonText: { color: colors.background, fontSize: 15, fontWeight: "800" }, state: { minHeight: 150, borderWidth: 1, borderColor: colors.border, borderRadius: 8, padding: 20, alignItems: "center", justifyContent: "center", gap: 8 }, muted: { color: colors.muted, fontSize: 14, lineHeight: 20, textAlign: "center" }, error: { color: colors.danger, fontSize: 14, lineHeight: 20, textAlign: "center" } });
