"use client";

import type { Team } from "@sports-fiesta/domain";
import { Activity, ArrowLeft, ArrowUpRight, CalendarPlus, CheckCircle2, ChevronRight, Clock3, Flag, Goal, Hand, LoaderCircle, Medal, Pencil, Sparkles, Sword, Swords, Timer, Trash2, Volleyball, type LucideIcon } from "lucide-react";
import Link from "next/link";
import { useState } from "react";
import { toast } from "sonner";
import { ContentSkeleton, DataError } from "@/components/data-state";
import { MatchStatusBadge } from "@/components/match-status-badge";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Field, FieldGroup, FieldLabel } from "@/components/ui/field";
import { Select, SelectContent, SelectGroup, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { callOrganizerCommand, usePrivateCollection } from "@/lib/organizer-data";
import { ACTIVITY_SPORTS, getActivityEvent, type ActivityFixture, type ActivityRecord } from "@/lib/activity-events";
import type { PublicMatch } from "@/lib/web-types";

const sports = [
  { value: "football", label: "Football", icon: Goal, card: "border-orange-500/15 bg-orange-500/10", iconTone: "border-orange-400/25 bg-orange-500/15 text-orange-400", textTone: "text-orange-300", line: "bg-orange-400" },
  { value: "handball", label: "Handball", icon: Hand, card: "border-teal-400/15 bg-teal-500/10", iconTone: "border-teal-300/25 bg-teal-500/15 text-teal-300", textTone: "text-teal-200", line: "bg-teal-300" },
  { value: "cricket", label: "Cricket", icon: Sword, card: "border-amber-400/15 bg-amber-500/10", iconTone: "border-amber-300/25 bg-amber-500/15 text-amber-300", textTone: "text-amber-200", line: "bg-amber-300" },
  { value: "throwball", label: "Throwball", icon: Volleyball, card: "border-rose-400/15 bg-rose-500/10", iconTone: "border-rose-300/25 bg-rose-500/15 text-rose-300", textTone: "text-rose-200", line: "bg-rose-300" },
] as const;
const stages = [{ value: "league", label: "League" }, { value: "third-place", label: "Third place" }, { value: "final", label: "Final" }];
const activityCardStyles = [
  { icon: Sparkles, card: "border-fuchsia-400/15 bg-fuchsia-500/10", iconTone: "border-fuchsia-300/25 bg-fuchsia-500/15 text-fuchsia-300", textTone: "text-fuchsia-200", line: "bg-fuchsia-300" },
  { icon: Medal, card: "border-lime-400/15 bg-lime-500/10", iconTone: "border-lime-300/25 bg-lime-500/15 text-lime-300", textTone: "text-lime-200", line: "bg-lime-300" },
  { icon: Flag, card: "border-sky-400/15 bg-sky-500/10", iconTone: "border-sky-300/25 bg-sky-500/15 text-sky-300", textTone: "text-sky-200", line: "bg-sky-300" },
  { icon: Timer, card: "border-violet-400/15 bg-violet-500/10", iconTone: "border-violet-300/25 bg-violet-500/15 text-violet-300", textTone: "text-violet-200", line: "bg-violet-300" },
] as const;

type SportKey = (typeof sports)[number]["value"];

export function OrganizerMatches({ sportPage }: { sportPage?: SportKey } = {}) {
  const teams = usePrivateCollection<Team>("teams");
  const matches = usePrivateCollection<PublicMatch>("matches");
  const activities = usePrivateCollection<ActivityRecord>("awards");
  const [sport, setSport] = useState<string>(sportPage ?? "football"); const [home, setHome] = useState(""); const [away, setAway] = useState(""); const [stage, setStage] = useState("league");
  const [pending, setPending] = useState(false); const [editing, setEditing] = useState<PublicMatch | null>(null); const [deleting, setDeleting] = useState<PublicMatch | null>(null); const [deletingActivity, setDeletingActivity] = useState<ActivityFixture | null>(null);

  async function create(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault(); setPending(true);
    try { await callOrganizerCommand("createMatch", { sport, homeTeamId: home, awayTeamId: away, stage }); toast.success("Fixture created."); setHome(""); setAway(""); setStage("league"); }
    catch (cause) { toast.error(cause instanceof Error ? cause.message : "Fixture creation failed."); } finally { setPending(false); }
  }
  async function remove() {
    if (!deleting) return; setPending(true);
    try { await callOrganizerCommand("deleteMatch", { matchId: deleting.id }); toast.success("Fixture deleted."); setDeleting(null); }
    catch (cause) { toast.error(cause instanceof Error ? cause.message : "Fixture deletion failed."); } finally { setPending(false); }
  }
  async function removeActivityFixture() {
    if (!deletingActivity) return; setPending(true);
    try { await callOrganizerCommand("deleteActivityFixture", { sport: deletingActivity.sport, eventId: deletingActivity.eventId }); toast.success("Special-event fixture deleted."); setDeletingActivity(null); }
    catch (cause) { toast.error(cause instanceof Error ? cause.message : "Fixture deletion failed."); } finally { setPending(false); }
  }
  if (teams.loading || matches.loading || activities.loading) return <ContentSkeleton />;
  const error = teams.error || matches.error || activities.error; if (error) return <DataError message={error} retry={matches.retry} />;
  const sortedMatches = [...matches.data].sort((a, b) => (a.matchNumber ?? a.id).localeCompare(b.matchNumber ?? b.id));
  const selectedSport = sportPage ? sports.find((sport) => sport.value === sportPage) : undefined;
  return <div className="mx-auto flex w-full max-w-7xl flex-col gap-6">
    {selectedSport ? <div><Button nativeButton={false} variant="ghost" className="mb-2 -ml-3" render={<Link href="/organizer/matches" />}><ArrowLeft data-icon="inline-start" />All sports</Button><h1 className="text-2xl font-semibold">{selectedSport.label} fixtures</h1><p className="mt-1 text-sm text-muted-foreground">Live, upcoming, and completed {selectedSport.label.toLowerCase()} fixtures.</p></div> : <div><h1 className="text-2xl font-semibold">Matches</h1><p className="mt-1 text-sm text-muted-foreground">Build fixtures, then open the scoring console when teams are ready.</p></div>}
    <Card className="overflow-hidden border-border/70 shadow-sm"><CardHeader className="border-b bg-muted/25"><CardTitle className="flex items-center gap-2"><span className="grid size-8 place-items-center rounded-lg bg-primary text-primary-foreground"><CalendarPlus className="size-4" /></span>Create fixture</CardTitle><CardDescription>Follow the match flow: sport, teams, then stage.</CardDescription></CardHeader><CardContent className="p-4 sm:p-6"><form onSubmit={create} className="space-y-5">
      <div className="rounded-2xl border bg-muted/20 p-4"><p className="mb-3 text-xs font-bold uppercase tracking-wider text-muted-foreground">1. Pick the sport</p><SelectField label="Sport" value={sport} onChange={setSport} items={sports} /></div>
      <div className="rounded-2xl border bg-background p-4 shadow-sm"><p className="mb-3 text-xs font-bold uppercase tracking-wider text-muted-foreground">2. Choose the matchup</p><div className="grid items-end gap-3 md:grid-cols-[1fr_auto_1fr]"><SelectField label="Home team" value={home} onChange={setHome} items={teams.data.map((team) => ({ value: team.id, label: team.name }))} /><div className="mx-auto flex size-11 items-center justify-center rounded-full border-4 border-background bg-primary text-xs font-black text-primary-foreground shadow-md md:mb-0">VS</div><SelectField label="Away team" value={away} onChange={setAway} items={teams.data.filter((team) => team.id !== home).map((team) => ({ value: team.id, label: team.name }))} /></div></div>
      <div className="rounded-2xl border bg-muted/20 p-4"><p className="mb-3 text-xs font-bold uppercase tracking-wider text-muted-foreground">3. Set the stage</p><div className="grid gap-4 md:grid-cols-[1fr_auto]"><SelectField label="Tournament stage" value={stage} onChange={setStage} items={stages} /><Button type="submit" size="lg" className="md:self-end" disabled={pending || !home || !away || home === away}>{pending ? <LoaderCircle data-icon="inline-start" className="animate-spin" /> : <Swords data-icon="inline-start" />}{pending ? "Creating" : "Create fixture"}</Button></div></div>
    </form></CardContent></Card>
    <section className="flex flex-col gap-5">{selectedSport ? <SportFixtureSection title={selectedSport.label} matches={sortedMatches.filter((match) => match.sport === selectedSport.value)} teams={teams.data} onEdit={setEditing} onDelete={setDeleting} /> : <><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-lg font-semibold">Sports & events</h2><p className="text-sm text-muted-foreground">Open a sport to manage fixtures or create a special-event fixture.</p></div><Badge variant="outline">{matches.data.length + activities.data.filter((record) => record.type === "activity-fixture").length} fixtures</Badge></div><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{sports.map((sport) => <SportCard key={sport.value} sport={sport} count={sortedMatches.filter((match) => match.sport === sport.value).length} />)}{ACTIVITY_SPORTS.map((sport, index) => <SportCard key={sport.id} sport={{ value: sport.id, label: sport.label, ...activityCardStyles[index] }} count={activities.data.filter((record) => record.type === "activity-fixture" && record.sport === sport.id).length} />)}</div><GlobalFixtureBoard matches={sortedMatches} activities={activities.data.filter((record): record is ActivityFixture => record.type === "activity-fixture")} teams={teams.data} onEdit={setEditing} onDelete={setDeleting} onDeleteActivity={setDeletingActivity} /></>}
    </section>
    {editing ? <EditFixtureDialog key={editing.id} match={editing} teams={teams.data} close={() => setEditing(null)} /> : null}
    <Dialog open={Boolean(deleting)} onOpenChange={(open) => !open && setDeleting(null)}><DialogContent><DialogHeader><DialogTitle>Delete this fixture?</DialogTitle><DialogDescription>This permanently removes {deleting ? `${teams.data.find((team) => team.id === deleting.homeTeamId)?.name ?? "Home"} vs ${teams.data.find((team) => team.id === deleting.awayTeamId)?.name ?? "Away"}` : "this fixture"}. Any scoring data will be lost.</DialogDescription></DialogHeader><DialogFooter><Button variant="outline" onClick={() => setDeleting(null)} disabled={pending}>Cancel</Button><Button variant="destructive" onClick={remove} disabled={pending}>{pending ? <LoaderCircle data-icon="inline-start" className="animate-spin" /> : <Trash2 data-icon="inline-start" />}Delete fixture</Button></DialogFooter></DialogContent></Dialog>
    <Dialog open={Boolean(deletingActivity)} onOpenChange={(open) => !open && setDeletingActivity(null)}><DialogContent><DialogHeader><DialogTitle>Delete this special-event fixture?</DialogTitle><DialogDescription>This removes the fixture, any saved result, and its points from standings. You can create it again afterward.</DialogDescription></DialogHeader><DialogFooter><Button variant="outline" onClick={() => setDeletingActivity(null)} disabled={pending}>Cancel</Button><Button variant="destructive" onClick={removeActivityFixture} disabled={pending}>{pending ? <LoaderCircle data-icon="inline-start" className="animate-spin" /> : <Trash2 data-icon="inline-start" />}Delete fixture</Button></DialogFooter></DialogContent></Dialog>
  </div>;
}

function FixtureGrid({ matches, teams, empty, onEdit, onDelete }: { matches: PublicMatch[]; teams: Team[]; empty: string; onEdit: (match: PublicMatch) => void; onDelete: (match: PublicMatch) => void }) {
  if (!matches.length) return <Card className="border-dashed shadow-none"><CardContent className="py-12 text-center text-sm text-muted-foreground">{empty}</CardContent></Card>;
  return <div className="grid gap-3 lg:grid-cols-2">{matches.map((match) => { const home = teams.find((team) => team.id === match.homeTeamId); const away = teams.find((team) => team.id === match.awayTeamId); const editable = match.status === "scheduled"; return <Card key={match.id} className="group overflow-hidden border-border/70 shadow-none transition-all hover:border-primary/40 hover:shadow-md"><CardContent className="p-0"><Link href={`/organizer/matches/${match.id}`} className="block p-5"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">{match.matchNumber ?? "Match"} · {match.sport} · {match.stage}</p><div className="mt-3 flex items-center gap-2 font-semibold"><span>{home?.shortName ?? "HOME"}</span><span className="rounded bg-muted px-1.5 py-0.5 text-[10px] text-muted-foreground">VS</span><span>{away?.shortName ?? "AWAY"}</span></div></div><MatchStatusBadge status={match.status} /></div><div className="mt-4 flex items-center justify-between border-t pt-3 text-sm text-muted-foreground"><span>Open scoring console</span><ChevronRight className="transition-transform group-hover:translate-x-1" /></div></Link>{editable ? <div className="flex gap-2 border-t bg-muted/20 px-5 py-2.5"><Button variant="ghost" size="sm" onClick={() => onEdit(match)}><Pencil data-icon="inline-start" />Edit</Button><Button variant="ghost" size="sm" className="text-destructive hover:bg-destructive/10 hover:text-destructive" onClick={() => onDelete(match)}><Trash2 data-icon="inline-start" />Delete</Button></div> : null}</CardContent></Card>; })}</div>;
}

function SportCard({ sport, count, countLabel = "fixture" }: { sport: { value: string; label: string; icon: LucideIcon; card: string; iconTone: string; textTone: string; line: string }; count: number; countLabel?: string }) {
  const Icon = sport.icon;
  return <Link href={`/organizer/sports/${sport.value}`} className={`group relative block overflow-hidden rounded-2xl border p-5 text-left shadow-sm transition-all duration-200 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring ${sport.card} hover:-translate-y-0.5 hover:brightness-110 hover:shadow-md`}><div className="flex items-center justify-between gap-3"><span className={`grid size-12 shrink-0 place-items-center rounded-xl border ${sport.iconTone}`}><Icon className="size-6" /></span><span className={`grid size-9 shrink-0 place-items-center rounded-full border ${sport.iconTone} transition-transform duration-200 group-hover:translate-x-0.5 group-hover:-translate-y-0.5`}><ArrowUpRight className="size-4" /></span></div><div className="mt-8"><p className={`text-xl font-bold tracking-tight ${sport.textTone}`}>{sport.label}</p><p className="mt-1 text-sm text-white/55">{count ? `${count} ${countLabel}${count === 1 ? "" : "s"}` : `No ${countLabel}s yet`}</p></div><span className={`absolute bottom-0 left-5 right-5 h-0.5 rounded-full ${sport.line} opacity-0 transition-opacity duration-200 group-hover:opacity-100`} /></Link>;
}

function SportFixtureSection({ title, matches, teams, onEdit, onDelete }: { title: string; matches: PublicMatch[]; teams: Team[]; onEdit: (match: PublicMatch) => void; onDelete: (match: PublicMatch) => void }) {
  const live = matches.filter((match) => ["live", "innings-break", "super-over"].includes(match.status));
  const upcoming = matches.filter((match) => match.status === "scheduled");
  const completed = matches.filter((match) => match.status === "completed");
  return <section className="pt-2"><div className="mb-4 flex items-center justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-muted-foreground">Selected sport</p><h3 className="mt-1 text-xl font-bold">{title} fixtures</h3></div><Badge variant={live.length ? "destructive" : "secondary"}>{live.length} live</Badge></div><Tabs defaultValue="live" className="flex-col"><TabsList className="mb-4 inline-flex h-auto w-full flex-wrap items-center justify-start rounded-xl bg-muted p-1 text-muted-foreground sm:w-fit"><TabsTrigger value="live" className="min-h-10 flex-1 gap-2 px-3 sm:flex-none"><Activity className="size-4" />Live <Badge variant="secondary">{live.length}</Badge></TabsTrigger><TabsTrigger value="upcoming" className="min-h-10 flex-1 gap-2 px-3 sm:flex-none"><Clock3 className="size-4" />Upcoming <Badge variant="secondary">{upcoming.length}</Badge></TabsTrigger><TabsTrigger value="completed" className="min-h-10 flex-1 gap-2 px-3 sm:flex-none"><CheckCircle2 className="size-4" />Completed <Badge variant="secondary">{completed.length}</Badge></TabsTrigger></TabsList><TabsContent value="live"><FixtureGrid matches={live} teams={teams} empty={`No live ${title.toLowerCase()} fixtures.`} onEdit={onEdit} onDelete={onDelete} /></TabsContent><TabsContent value="upcoming"><FixtureGrid matches={upcoming} teams={teams} empty={`No upcoming ${title.toLowerCase()} fixtures.`} onEdit={onEdit} onDelete={onDelete} /></TabsContent><TabsContent value="completed"><FixtureGrid matches={completed} teams={teams} empty={`No completed ${title.toLowerCase()} fixtures.`} onEdit={onEdit} onDelete={onDelete} /></TabsContent></Tabs></section>;
}

function GlobalFixtureBoard({ matches, activities, teams, onEdit, onDelete, onDeleteActivity }: { matches: PublicMatch[]; activities: ActivityFixture[]; teams: Team[]; onEdit: (match: PublicMatch) => void; onDelete: (match: PublicMatch) => void; onDeleteActivity: (fixture: ActivityFixture) => void }) {
  const isLiveMatch = (match: PublicMatch) => ["live", "innings-break", "super-over"].includes(match.status);
  const liveMatches = matches.filter(isLiveMatch); const upcomingMatches = matches.filter((match) => match.status === "scheduled"); const completedMatches = matches.filter((match) => match.status === "completed");
  const liveActivities = activities.filter((fixture) => fixture.status === "live"); const upcomingActivities = activities.filter((fixture) => fixture.status === "scheduled"); const completedActivities = activities.filter((fixture) => fixture.status === "completed");
  return <section className="border-t pt-6"><div className="mb-5 flex flex-wrap items-end justify-between gap-3"><div><h2 className="text-lg font-semibold">All fixtures</h2><p className="mt-1 text-sm text-muted-foreground">Every sport in one place. Use the status tabs to find the fixture you need.</p></div><Badge variant={liveMatches.length + liveActivities.length ? "destructive" : "secondary"}>{liveMatches.length + liveActivities.length} live</Badge></div><Tabs defaultValue="live" className="flex-col"><TabsList className="mb-4 inline-flex h-auto w-full flex-wrap items-center justify-start rounded-xl bg-muted p-1 text-muted-foreground sm:w-fit"><TabsTrigger value="live" className="min-h-10 flex-1 gap-2 px-3 sm:flex-none"><Activity className="size-4" />Live <Badge variant="secondary">{liveMatches.length + liveActivities.length}</Badge></TabsTrigger><TabsTrigger value="upcoming" className="min-h-10 flex-1 gap-2 px-3 sm:flex-none"><Clock3 className="size-4" />Upcoming <Badge variant="secondary">{upcomingMatches.length + upcomingActivities.length}</Badge></TabsTrigger><TabsTrigger value="completed" className="min-h-10 flex-1 gap-2 px-3 sm:flex-none"><CheckCircle2 className="size-4" />Completed <Badge variant="secondary">{completedMatches.length + completedActivities.length}</Badge></TabsTrigger></TabsList><TabsContent value="live"><GlobalFixtureGrid matches={liveMatches} activities={liveActivities} teams={teams} empty="No live fixtures across any sport." onEdit={onEdit} onDelete={onDelete} onDeleteActivity={onDeleteActivity} /></TabsContent><TabsContent value="upcoming"><GlobalFixtureGrid matches={upcomingMatches} activities={upcomingActivities} teams={teams} empty="No upcoming fixtures across any sport." onEdit={onEdit} onDelete={onDelete} onDeleteActivity={onDeleteActivity} /></TabsContent><TabsContent value="completed"><GlobalFixtureGrid matches={completedMatches} activities={completedActivities} teams={teams} empty="No completed fixtures across any sport." onEdit={onEdit} onDelete={onDelete} onDeleteActivity={onDeleteActivity} /></TabsContent></Tabs></section>;
}

function GlobalFixtureGrid({ matches, activities, teams, empty, onEdit, onDelete, onDeleteActivity }: { matches: PublicMatch[]; activities: ActivityFixture[]; teams: Team[]; empty: string; onEdit: (match: PublicMatch) => void; onDelete: (match: PublicMatch) => void; onDeleteActivity: (fixture: ActivityFixture) => void }) {
  if (!matches.length && !activities.length) return <Card className="border-dashed shadow-none"><CardContent className="py-12 text-center text-sm text-muted-foreground">{empty}</CardContent></Card>;
  return <div className="grid gap-3 lg:grid-cols-2">{matches.map((match) => { const home = teams.find((team) => team.id === match.homeTeamId); const away = teams.find((team) => team.id === match.awayTeamId); const editable = match.status === "scheduled"; return <Card key={match.id} className="overflow-hidden border-border/70 shadow-none"><CardContent className="p-0"><Link href={`/organizer/matches/${match.id}`} className="block p-5"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">{match.sport} · {match.stage}</p><p className="mt-2 font-semibold">{home?.shortName ?? "HOME"} <span className="mx-1 text-muted-foreground">vs</span> {away?.shortName ?? "AWAY"}</p></div><MatchStatusBadge status={match.status} /></div></Link>{editable ? <div className="grid grid-cols-2 border-t bg-muted/20"><Button variant="ghost" size="sm" className="rounded-none" onClick={() => onEdit(match)}><Pencil data-icon="inline-start" />Edit</Button><Button variant="ghost" size="sm" className="rounded-none text-destructive hover:bg-destructive/10 hover:text-destructive" onClick={() => onDelete(match)}><Trash2 data-icon="inline-start" />Delete</Button></div> : null}</CardContent></Card>; })}{activities.map((fixture) => { const event = getActivityEvent(fixture.sport, fixture.eventId); return <Card key={fixture.id} className="overflow-hidden border-border/70 shadow-none"><CardContent className="p-0"><div className="p-5"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">{fixture.sport.replaceAll("-", " ")} · {event?.kind === "relay" ? "Team relay" : "Individual event"}</p><p className="mt-2 font-semibold">{event?.name ?? "Special event"}</p></div><Badge variant={fixture.status === "live" ? "destructive" : fixture.status === "completed" ? "secondary" : "outline"}>{fixture.status}</Badge></div></div><div className="grid grid-cols-2 border-t bg-muted/20"><Button nativeButton={false} variant="ghost" size="sm" className="rounded-none" render={<Link href={`/organizer/sports/${fixture.sport}`}><Pencil data-icon="inline-start" />Edit</Link>} /><Button variant="ghost" size="sm" className="rounded-none text-destructive hover:bg-destructive/10 hover:text-destructive" onClick={() => onDeleteActivity(fixture)}><Trash2 data-icon="inline-start" />Delete</Button></div></CardContent></Card>; })}</div>;
}

function EditFixtureDialog({ match, teams, close }: { match: PublicMatch; teams: Team[]; close: () => void }) {
  const [sport, setSport] = useState<string>(match.sport); const [home, setHome] = useState(match.homeTeamId); const [away, setAway] = useState(match.awayTeamId); const [stage, setStage] = useState<string>(match.stage); const [pending, setPending] = useState(false);
  const openChange = (open: boolean) => { if (!open) close(); };
  async function save() { setPending(true); try { await callOrganizerCommand("updateMatch", { matchId: match.id, sport, homeTeamId: home, awayTeamId: away, stage }); toast.success("Fixture updated."); close(); } catch (cause) { toast.error(cause instanceof Error ? cause.message : "Fixture update failed."); } finally { setPending(false); } }
  return <Dialog open onOpenChange={openChange}><DialogContent><DialogHeader><DialogTitle>Edit scheduled fixture</DialogTitle><DialogDescription>Update the matchup before scoring begins.</DialogDescription></DialogHeader><FieldGroup className="py-2"><SelectField label="Sport" value={sport} onChange={setSport} items={sports} /><div className="grid gap-3 sm:grid-cols-2"><SelectField label="Home team" value={home} onChange={setHome} items={teams.map((team) => ({ value: team.id, label: team.name }))} /><SelectField label="Away team" value={away} onChange={setAway} items={teams.filter((team) => team.id !== home).map((team) => ({ value: team.id, label: team.name }))} /></div><SelectField label="Stage" value={stage} onChange={setStage} items={stages} /></FieldGroup><DialogFooter><Button variant="outline" onClick={close} disabled={pending}>Cancel</Button><Button onClick={save} disabled={pending || !sport || !home || !away || home === away}>{pending ? <LoaderCircle data-icon="inline-start" className="animate-spin" /> : <Pencil data-icon="inline-start" />}Save changes</Button></DialogFooter></DialogContent></Dialog>;
}

function SelectField({ label, value, onChange, items }: { label: string; value: string; onChange: (value: string) => void; items: ReadonlyArray<{ value: string; label: string }> }) { return <Field><FieldLabel>{label}</FieldLabel><Select value={value} onValueChange={(next) => onChange(next ?? "")}><SelectTrigger className="h-11 w-full"><SelectValue placeholder={`Choose ${label.toLowerCase()}`} /></SelectTrigger><SelectContent><SelectGroup>{items.map((item) => <SelectItem key={item.value} value={item.value}>{item.label}</SelectItem>)}</SelectGroup></SelectContent></Select></Field>; }
