import AsyncStorage from "@react-native-async-storage/async-storage";
import { collection, doc, onSnapshot, type DocumentData } from "firebase/firestore";
import { httpsCallable } from "firebase/functions";
import { useEffect, useState } from "react";
import { db, functions, privatePath } from "@/lib/firebase";
export function usePrivateCollection<T extends DocumentData>(name: string) { const [data, setData] = useState<T[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); useEffect(() => { const key = `private-${name}`; AsyncStorage.getItem(key).then((cached) => { if (cached) setData(JSON.parse(cached) as T[]); }).finally(() => setLoading(false)); return onSnapshot(collection(db, privatePath(name)), (snapshot) => { const rows = snapshot.docs.map((item) => ({ id: item.id, ...item.data() }) as unknown as T); setData(rows); setLoading(false); setError(null); void AsyncStorage.setItem(key, JSON.stringify(rows)); }, (cause) => { setError(cause.message); setLoading(false); }); }, [name]); return { data, loading, error }; }
export function usePrivateDocument<T extends DocumentData>(name: string, id: string) { const [data, setData] = useState<T | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); useEffect(() => onSnapshot(doc(db, privatePath(name, id)), (snapshot) => { setData(snapshot.exists() ? ({ id: snapshot.id, ...snapshot.data() } as unknown as T) : null); setLoading(false); setError(null); }, (cause) => { setError(cause.message); setLoading(false); }), [id, name]); return { data, loading, error }; }
export function useTournament<T extends DocumentData>() { const [data, setData] = useState<T | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); useEffect(() => onSnapshot(doc(db, privatePath()), (snapshot) => { setData(snapshot.exists() ? (snapshot.data() as T) : null); setLoading(false); setError(null); }, (cause) => { setError(cause.message); setLoading(false); }), []); return { data, loading, error }; }
export async function command<T = unknown>(name: string, data: Record<string, unknown> = {}) { return (await httpsCallable<Record<string, unknown>, T>(functions, name)(data)).data; }
export function revision(match: MatchLike, data: Record<string, unknown> = {}) { return { ...data, matchId: match.id, expectedRevision: match.revision, commandId: crypto.randomUUID() }; }
type MatchLike = { id: string; revision: number };
